# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\x12\n\x10OccupancyRequest\"T\n\x0cSegmentState\x12\x12\n\nsegment_id\x18\x01 \x01(\r\x12\x17\n\x0foccupancy_ratio\x18\x02 \x01(\x02\x12\x17\n\x0f\x61\x63tive_vehicles\x18\x03 \x01(\r\"T\n\x11OccupancyResponse\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12)\n\x08segments\x18\x02 \x03(\x0b\x32\x17.telemetry.SegmentState2`\n\x10TelemetryService\x12L\n\x0fGetOccupancyMap\x12\x1b.telemetry.OccupancyRequest\x1a\x1c.telemetry.OccupancyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCCUPANCYREQUEST']._serialized_start=30
  _globals['_OCCUPANCYREQUEST']._serialized_end=48
  _globals['_SEGMENTSTATE']._serialized_start=50
  _globals['_SEGMENTSTATE']._serialized_end=134
  _globals['_OCCUPANCYRESPONSE']._serialized_start=136
  _globals['_OCCUPANCYRESPONSE']._serialized_end=220
  _globals['_TELEMETRYSERVICE']._serialized_start=222
  _globals['_TELEMETRYSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
